#!/usr/bin/env python3


import argparse
from random import choice, randint, gauss


MEAN = 5
STANDARD_DEVIATION = 5


def parse_args():
    """
    Parses arguments given by the user in the command line.
    """
    parser = argparse.ArgumentParser(
        description='Helper script to generate random deliveries files.')
    parser.add_argument('number', type=int, help='number of deliveries')
    parser.add_argument('max', type=int, help='-max <= x, y <= max')
    return parser.parse_args()


def generate_deliveries(number, max_):
    """
    Generates the file lines for the deliveries with random deliveries.
    """
    lines = []
    product_count = 0
    for _ in range(number):
        line_tokens = []
        n_packages = choice((1, 2, 3, 4))
        line_tokens.append(str(n_packages))
        for count in range(n_packages):
            product = 'product{}'.format(product_count)
            line_tokens.append(product)
            product_count += 1
        line_tokens.append(str(randint(-max_, max_)))
        line_tokens.append(str(randint(-max_, max_)))
        lines.append(' '.join(line_tokens))
    return lines, product_count


def generate_weights(n_products):
    """
    Generates the file lines for the weights with random weights.
    """
    lines = []
    for i in range(n_products):
        line_tokens = []
        line_tokens.append('product{}'.format(i))
        weight = sorted((0, gauss(MEAN, STANDARD_DEVIATION), 50))[1]
        line_tokens.append(str(round(weight, 2)))
        lines.append(' '.join(line_tokens))
    return lines


def main():
    args = parse_args()
    deliveries_lines, product_count = generate_deliveries(
        args.number, args.max)
    weights_lines = generate_weights(product_count)
    with open('deliveries.txt', 'w') as file_:
        file_.write(str(len(deliveries_lines)))
        file_.write('\n')
        file_.write('\n'.join(deliveries_lines))
        file_.write('\n')
        file_.write(str(product_count))
        file_.write('\n')
        file_.write('\n'.join(weights_lines))
        file_.write('\n')


if __name__ == '__main__':
    main()
